config/routes.rb
Dispatcher::Application.routes.draw do
  
  resources :feedbacks do
    member do
      put :star
    end
  end

  resources :coordinations

  devise_for :coordinators
  resources :coordinators do
    resources :coordinations
  end

  resources :categories

  resources :notes

  resources :proficiencies

  resources :languages do
    resources :teams
  end

  devise_for :residents
  resources :residents do
    collection do
      post :populate
    end
  end

  resources :task_waivers

  resources :jobs do
    resources :notes
    member do
      put :start
      put :finish
    end
    collection do
      post :export
    end
  end

  resources :steps do
    member do
      put 'move_up'
    end
  end

  resources :phase_templates do
    resources :steps
    resources :units do
      post :apply
    end
  end

  resources :signatures do
    collection do
      post :search
    end
  end

  resources :waivers do
    resources :signatures
  end

  resources :deployments

  devise_for :team_admins, :controllers => { :registrations => :team_admin_registrations, :sessions => :sessions }
  resources :team_admins do
    member do
      get 'activate'
      get 'deactivate'
    end
  end

  match '/registration' => 'tasks#registration', :as => 'assistance_registration'
  match '/request' => 'tasks#intake', :as => 'request_task', :via => :post
  match '/legal_intake' => 'tasks#legal_intake', :as => 'legal_intake', :via => :put
  match '/finish_intake' => 'tasks#finish_intake', :as => 'finish_intake', :via => :put
  resources :operations_centers do
    resources :assignments
  end

  resources :assignments

  resources :aptitudes

  resources :dispatches

  resources :tasks

  resources :skills

  resources :roles do
    member do
      post :join
    end
  end

  resources :teams do
    resources :roles
  end

  devise_for :people, :controllers => { :registrations => :registrations, :sessions => :sessions }
  resources :people do
    collection do
      get :home
      get :email_export
    end
  end

  resources :units do
    resources :residents
    resources :jobs
    member do
      get :phase
    end
    collection do
      post :upload
      get :search
    end
  end

  resources :addresses do
    resources :units
    resources :jobs
  end

  resources :streets

  resources :neighborhoods do
    resources :operations_centers
  end

  resources :cities do
    resources :teams
    resources :deployments
  end
  
  match '/volunteer_introduction', :controller => 'dispatches', :action => 'volunteer_introduction'
  match '/about', :controller => 'dispatches', :action => 'about'
  match '/help', :controller => 'pages', :action => 'help'
  
  root :to => 'dispatches#introduction'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :person
  belongs_to :unit
  has_one :address, :through => :unit
  has_many :task_waivers
  has_many :waivers, :through => :task_waivers
  attr_accessible :person_id, :unit_id, :actual_end, :actual_start, :description, :name, :scheduled_end, :scheduled_start
  scope :alphabetical, :order => :name
  
  def self.common_tasks
    PhaseTemplate.find(8, 3, 1, 2, 5).map(&:tasks).flatten
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_team_admin!, :only => [:new, :edit, :create, :update, :destroy]
  before_filter :direct_user, :only => [:show, :index]
  def registration
    
  end
  
  def intake
    @resident = Resident.new :email => params[:email], :password => params[:password], :password_confirmation => params[:password_confirmation], :first_name => params[:first_name], :last_name => params[:last_name], :primary_phone_number => params[:primary_phone_number]
    if @resident.save
      ResidentRegistrationMailer.registration_receipt(@resident).deliver
      sign_in @resident
      @city = City.find params[:city_id]
      @street = @city.streets.find_or_create_by_name params[:street_name]
      @address = @street.addresses.find_or_create_by_street_number :street_number => params[:street_number], :zip_code => params[:zip_code]
      @unit = @address.units.find_or_create_by_name params[:unit_name]
      @unit.resident = @resident
      @unit.save
      params[:languages].andand.each do |language_id|
        @resident.proficiencies.create :language_id => language_id
      end
      session[:unit_id] = @unit.id
      session[:address_id] = @address.id
    else
      render :action => 'registration'
    end
  end
  
  def legal_intake
    @address = Address.find session[:address_id]
    @address.update_attributes params[:address]
    session[:address_id] = nil
    @unit = Unit.find session[:unit_id]
    @unit.needs_met = params[:needs_met] == 'yes'
    @unit.power_on = params[:power] == 'yes'
    @unit.heater_needed = params[:heater] == 'yes'
    @unit.save
    if params[:vehicles].present?
      current_resident.vehicles = params[:vehicles]
    end
    current_resident.has_phone = params[:has_phone] == 'yes'
    current_resident.has_smart_phone = params[:has_smart_phone] == 'yes'
    current_resident.has_internet_access = params[:has_internet_access] == 'yes'
    current_resident.save
  end
    
  def finish_intake
    @unit = Unit.find session[:unit_id]
    session[:unit_id] = nil
    @unit.update_attributes params[:unit]
    redirect_to @unit
  end

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to :action => :index, notice: 'Task created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
  
  private
  def direct_user
    return true if current_person || current_team_admin
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>
<%= button_to 'New Task', new_task_path, :method => :get, :class => 'right new_button' %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<%= paginate @tasks %>
<% @tasks.each do |task| %>
  <tr class="<%= cycle 'light-gray', 'white' %>">
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= paginate @tasks %>
<br />

app/views/tasks/intake.html.erb
Thanks, we have saved the details of your request.  We will contact you by email or phone when we have information for you.

Can you specify which neighborhood you are in?
<%= form_for @address, :url => legal_intake_path do |f| %>
  <%= f.select :neighborhood_id, options_from_collection_for_select(@address.city.neighborhoods.alphabetical, :id, :name, @address.neighborhood_id), :include_blank => 'Choose Neighborhood' %><br>
  Have your needs been met? &nbsp;&nbsp;&nbsp;&nbsp;
  <%= radio_button_tag :needs_met, :yes %><%= label_tag :needs_met, :yes %>
  <%= radio_button_tag :needs_met, :no %><%= label_tag :needs_met, :no %>
  <br>
  Is your power on?&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= radio_button_tag :power, :yes %><%= label_tag :power, :yes %>
  <%= radio_button_tag :power, :no %><%= label_tag :power, :no %>
  <br>
  Do you need a heater?&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= radio_button_tag :heater, :yes %><%= label_tag :heater, :yes %>
  <%= radio_button_tag :heater, :no %><%= label_tag :heater, :no %>
  <br>
  Feel free to list any working vehicles you have.
  <%= text_field_tag :vehicles %>
  <br>
  What communication tools do you currently have?<br>
  Phone? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= radio_button_tag :has_phone, :yes %><%= label_tag :has_phone, :yes %>
  <%= radio_button_tag :has_phone, :no %><%= label_tag :has_phone, :no %>
  <br>
  Smart Phone? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= radio_button_tag :has_smart_phone, :yes %><%= label_tag :has_smart_phone, :yes %>
  <%= radio_button_tag :has_smart_phone, :no %><%= label_tag :has_phone, :no %>
  <br>
  Internet Access? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= radio_button_tag :has_internet_access, :yes %><%= label_tag :has_internet_access, :yes %>
  <%= radio_button_tag :has_internet_access, :no %><%= label_tag :has_internet_access, :no %><br>
  <%= f.submit 'Submit Information or Skip' %>
<% end %>

app/views/tasks/legal_intake.html.erb
<%= form_for @unit, :url => finish_intake_path do |f| %>
  Is your home livable? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.radio_button :livable, true %><%= f.label :livable, 'yes' %>
  <%= f.radio_button :livable, false %><%= f.label :livable, 'no' %>
  <br>
  Do you plan to return to live there?
  <%= f.radio_button :plan_to_return, true %><%= f.label :plan_to_return, 'yes' %>
  <%= f.radio_button :plan_to_return, false %><%= f.label :plan_to_return, 'no' %>
  <br>
  Do you need a carbon monoxide detector?
  <%= f.radio_button :need_carbon_monoxide_detector, true %><%= f.label :need_carbon_monoxide_detector, 'yes' %>
  <%= f.radio_button :need_carbon_monoxide_detector, false %><%= f.label :need_carbon_monoxide_detector, 'no' %>
  <br>
  Do you own or rent? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.radio_button :tenant_is_owner, true %><%= f.label :tenant_is_owner, 'own' %>
  <%= f.radio_button :tenant_is_owner, false %><%= f.label :tenant_is_owner, 'rent' %>
  <br>
  Do you have legal needs? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.text_area :legal_needs, :placeholder => 'Yes/No, Brief description, or detailed description of legal needs', :size => '40x3' %>
  <br>
  Do you have medical needs? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.text_area :medical_needs, :placeholder => 'Yes/No, Brief description, or detailed description of medical needs', :size => '40x3' %>
  <br>
  Do you have a FEMA number/id?&nbsp;
  <%= f.text_field :fema_number, :placeholder => '25-7073568', :size => 10 %>
  <br>
  Do you have insurance? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.text_field :insurance_situation, :placeholder => 'Yes/No, brief or detailed', :size => 45 %>
  <br>
  Have you contacted Rapid Response/311?
  <%= f.radio_button :rapid_response_contacted, true %><%= f.label :rapid_response_contacted, 'yes'%>
  <%= f.radio_button :rapid_response_contacted, false %><%= f.label :rapid_response_contacted, 'no' %>
  <br>
  What year was your home built?
  <%= f.date_select :year_built, :start_year => Time.now.year, :end_year => 1800, :discard_month => true, :include_blank => true %>
  <br>
  <%= f.submit 'Submit Information or Skip' %>
<% end %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/registration.html.erb
<% if @resident %>
  <div id="error_explanation">
    <% @resident.errors.full_messages.each do |error| %>
      <%= error %><br>
    <% end %>
  </div>
<% end %>
<%= form_tag request_task_path, :id => 'intake' do %>
  <%= text_field_tag :first_name, params[:first_name] %>
  <%= label_tag :first_name %><br>
  <%= text_field_tag :last_name, params[:last_name] %>
  <%= label_tag :last_name %><br>
  <%= text_field_tag :primary_phone_number, params[:primary_phone_number] %>
  <%= label_tag :primary_phone_number %><br>
  <%= email_field_tag :email, params[:email] %>
  <%= label_tag :email %>* (Either an email or a phone number is required)<br>
  <%= password_field_tag :password %>
  <%= label_tag :password, 'Please Choose a Password (at least 6 characters)' %>*<br>
  <%= password_field_tag :password_confirmation %>
  <%= label_tag :password_confirmation, 'Please Confirm the Password' %>*<hr>
  <%= text_field_tag :street_number, params[:street_number], :size => 3, :placeholder => '45' %>
  <%= text_field_tag :street_name, params[:street_name], :placeholder => 'Newberry Ln' %>
  <%= text_field_tag :unit_name, params[:unit_name], :size => 5, :placeholder => 'Apt 2A' %><br>
  &nbsp;&nbsp;&nbsp;&nbsp;<%= label_tag :street_number, '#' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= label_tag :street_name, 'Street' %>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= label_tag :unit_name, 'Unit' %><br>
  (Please capitalize and abbreviate street types: Rd, Ave, Ln, Pl, etc)<br>
  <em>Note: please put your street number and street name in the two separate boxes.  If your home has a unit number or name, put it in the third box.  Thanks for your cooperation!</em><br>
  
  <hr>
  <%= select_tag :city_id, options_from_collection_for_select(City.alphabetical, :id, :name, params[:city_id]), :include_blank => true %>
  <%= label_tag :city_id %>*<br>
  <%= text_field_tag :zip_code, params[:zip_code], :size => 6 %>
  <%= label_tag :zip_code, 'zip code' %><hr>

  Languages spoken in the house:<br>
  <% Language.all.each do |language| %>
    <%= check_box_tag 'languages[]', language.id %>
    <%= label_tag :languages, language.name %><br>
  <% end %>

  <%= submit_tag 'Submit Information' %>
  
<% end %>
<script type="text/javascript">
  $('#intake').validate({'rules': {
	  'password': {'required': true, 'minlength': 6},
	  'password_confirmation': {'required': true, 'minlength': 6},
	  'city_id': {'required': true}
	}});
</script>

app/views/tasks/show.html.erb
<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>