config/routes.rb
Dispatcher::Application.routes.draw do
  
  resources :feedbacks do
    member do
      put :star
    end
  end

  resources :coordinations

  devise_for :coordinators
  resources :coordinators do
    resources :coordinations
  end

  resources :categories

  resources :notes

  resources :proficiencies

  resources :languages do
    resources :teams
  end

  devise_for :residents
  resources :residents do
    collection do
      post :populate
    end
  end

  resources :task_waivers

  resources :jobs do
    resources :notes
    member do
      put :start
      put :finish
    end
    collection do
      post :export
    end
  end

  resources :steps do
    member do
      put 'move_up'
    end
  end

  resources :phase_templates do
    resources :steps
    resources :units do
      post :apply
    end
  end

  resources :signatures do
    collection do
      post :search
    end
  end

  resources :waivers do
    resources :signatures
  end

  resources :deployments

  devise_for :team_admins, :controllers => { :registrations => :team_admin_registrations, :sessions => :sessions }
  resources :team_admins do
    member do
      get 'activate'
      get 'deactivate'
    end
  end

  match '/registration' => 'tasks#registration', :as => 'assistance_registration'
  match '/request' => 'tasks#intake', :as => 'request_task', :via => :post
  match '/legal_intake' => 'tasks#legal_intake', :as => 'legal_intake', :via => :put
  match '/finish_intake' => 'tasks#finish_intake', :as => 'finish_intake', :via => :put
  resources :operations_centers do
    resources :assignments
  end

  resources :assignments

  resources :aptitudes

  resources :dispatches

  resources :tasks

  resources :skills

  resources :roles do
    member do
      post :join
    end
  end

  resources :teams do
    resources :roles
  end

  devise_for :people, :controllers => { :registrations => :registrations, :sessions => :sessions }
  resources :people do
    collection do
      get :home
      get :email_export
    end
  end

  resources :units do
    resources :residents
    resources :jobs
    member do
      get :phase
    end
    collection do
      post :upload
      get :search
    end
  end

  resources :addresses do
    resources :units
    resources :jobs
  end

  resources :streets

  resources :neighborhoods do
    resources :operations_centers
  end

  resources :cities do
    resources :teams
    resources :deployments
  end
  
  match '/volunteer_introduction', :controller => 'dispatches', :action => 'volunteer_introduction'
  match '/about', :controller => 'dispatches', :action => 'about'
  match '/help', :controller => 'pages', :action => 'help'
  
  root :to => 'dispatches#introduction'

end

app/views/shared/_coordinator_tabs.html.erb
<%= link_to 'teams', teams_path, :class => 'right tab' %>
<%= link_to 'jobs', jobs_path, :class => 'right tab' %>

app/views/shared/_person_resource_links.html.erb
<%= link_to 'waivers', waivers_path, :class => 'right tab' %>
<% if current_person.has_signed_waivers? %>
  <%= link_to 'neighborhoods', neighborhoods_path, :class => 'right tab' %>
  <%= link_to 'operations centers', operations_centers_path, :class => 'right tab' %>
  <%= link_to 'skills', skills_path, :class => 'right tab' %>
  <%= link_to 'dispatches', dispatches_path, :class => 'right tab' %>
  <%= link_to 'teams', teams_path, :class => 'right tab' %>
<% end %>

app/views/shared/_resident_resource_links.html.erb
<%= link_to 'waivers', waivers_path, :class => 'right tab' %>
<%= link_to 'my home', unit_path(current_resident.units.first), :class => 'right tab' %>

app/views/shared/_resource_links_bottom.html.erb
<%= clearfix %>
<div id="centers_tabs" class="tab_group">
  <%= link_to 'centers', operations_centers_path, :class => 'big tab bottom_links' %>
  <br>
  <%= link_to 'assignments', assignments_path, :class => 'tab bottom_links' %>
  <%= link_to 'coordinations', coordinations_path, :class => 'tab bottom_links' %>
</div>

<div id="addresses_tabs" class="tab_group">
  <%= link_to 'addresses', addresses_path, :class => 'big tab bottom_links' %>
  <br>
  <%= link_to 'streets', streets_path, :class => 'tab bottom_links' %>
  <%= link_to 'neighborhoods', neighborhoods_path, :class => 'tab bottom_links' %>
  <%= link_to 'cities', cities_path, :class => 'tab bottom_links' %>
</div>

<div id="waivers_tabs" class="tab_group">
  <%= link_to 'waivers', waivers_path, :class => 'big tab bottom_links' %>
  <br>
  <%= link_to 'signatures', signatures_path, :class => 'tab bottom_links' %>
  <%= link_to 'task-waivers', task_waivers_path, :class => 'tab bottom_links' %>
</div>

<%= link_to 'skills', skills_path, :class => 'right tab bottom_links' %>
<%= link_to 'aptitudes', aptitudes_path, :class => 'right tab bottom_links' %>
<%= link_to 'languages', languages_path, :class => 'right tab bottom_links' %>
<%= link_to 'steps', steps_path, :class => 'right tab bottom_links' %>
<%= link_to 'categories', categories_path, :class => 'right tab bottom_links' %>
<%= link_to 'notes', notes_path, :class => 'right tab bottom_links' %>
<%= link_to 'feedback', feedbacks_path, :class => 'right tab bottom_links' %>

app/views/shared/_resource_links_top.html.erb
<div id="people_tabs" class="tab_group">
  <%= link_to 'people', '',  :class => 'big tab top_links' %>
  <br>
  <%= link_to 'volunteers', people_path, :class => 'tab top_links' %>
  <%= link_to 'admins', team_admins_path, :class => 'tab top_links' %>
  <%= link_to 'residents', residents_path, :class => 'tab top_links' %>
  <%= link_to 'coordinators', coordinators_path, :class => 'tab top_links' %>
</div>
<div id="teams_tabs" class="tab_group">
  <%= link_to 'teams', teams_path, :class => 'big tab top_links' %>
  <br>
  <%= link_to 'deployments', deployments_path, :class => 'tab top_links' %>
  <%= link_to 'dispatches', dispatches_path(:filter => :unscheduled), :class => 'tab top_links' %>
  <%= link_to 'roles', roles_path, :class => 'tab top_links' %>
</div>
<div id="homes_tabs" class="tab_group">
  <%= link_to 'homes', units_path, :class => 'big tab top_links' %>
  <br>
  <%= link_to 'tasks', tasks_path, :class => 'tab top_links' %>
  <%= link_to 'phases', phase_templates_path, :class => 'tab top_links' %>
  <%= link_to 'jobs', jobs_path, :class => 'tab top_links' %>
</div>

<%= link_to 'add resident', new_resident_path, :class => 'right tab top_links', :id => 'add_resident' %>

app/views/shared/_tab_highlighter.html.erb
<% content_for :scripts do %>
  <script type="text/javascript">
    $(function() {
      highlightTab('<%= controller_name %>');
    });
  </script>
<% end %>

app/views/shared/about.html.erb
<p>
  This app, Disaster Dispatcher, is intended to help coordinate workers, who are doing jobs at homes.
</p>

<p>
  The goal is to prevent two (or more) teams from accidentally going to the same house.
</p>

<p>
  It can be difficult to efficiently coordinate volunteers (and paid workers) during the response to a disaster.  This system is a step that we hope will help efficiency.  It is quite a simple app, mainly used for tying together different pieces of information.  As our needs become more clear, we will incorporate whatever tools we can come up with.
</p>

<p>
  As we undergo our first launch (early December), this is roughly what the app does.  Volunteers can sign up and join teams, and indicate which skills they have.  Relief seekers can specify their address and their needs.  Then, coordinators can dispatch teams to do the work at those sites.
</p>