config/routes.rb
Dispatcher::Application.routes.draw do
  
  resources :feedbacks do
    member do
      put :star
    end
  end

  resources :coordinations

  devise_for :coordinators
  resources :coordinators do
    resources :coordinations
  end

  resources :categories

  resources :notes

  resources :proficiencies

  resources :languages do
    resources :teams
  end

  devise_for :residents
  resources :residents do
    collection do
      post :populate
    end
  end

  resources :task_waivers

  resources :jobs do
    resources :notes
    member do
      put :start
      put :finish
    end
    collection do
      post :export
    end
  end

  resources :steps do
    member do
      put 'move_up'
    end
  end

  resources :phase_templates do
    resources :steps
    resources :units do
      post :apply
    end
  end

  resources :signatures do
    collection do
      post :search
    end
  end

  resources :waivers do
    resources :signatures
  end

  resources :deployments

  devise_for :team_admins, :controllers => { :registrations => :team_admin_registrations, :sessions => :sessions }
  resources :team_admins do
    member do
      get 'activate'
      get 'deactivate'
    end
  end

  match '/registration' => 'tasks#registration', :as => 'assistance_registration'
  match '/request' => 'tasks#intake', :as => 'request_task', :via => :post
  match '/legal_intake' => 'tasks#legal_intake', :as => 'legal_intake', :via => :put
  match '/finish_intake' => 'tasks#finish_intake', :as => 'finish_intake', :via => :put
  resources :operations_centers do
    resources :assignments
  end

  resources :assignments

  resources :aptitudes

  resources :dispatches

  resources :tasks

  resources :skills

  resources :roles do
    member do
      post :join
    end
  end

  resources :teams do
    resources :roles
  end

  devise_for :people, :controllers => { :registrations => :registrations, :sessions => :sessions }
  resources :people do
    collection do
      get :home
      get :email_export
    end
  end

  resources :units do
    resources :residents
    resources :jobs
    member do
      get :phase
    end
    collection do
      post :upload
      get :search
    end
  end

  resources :addresses do
    resources :units
    resources :jobs
  end

  resources :streets

  resources :neighborhoods do
    resources :operations_centers
  end

  resources :cities do
    resources :teams
    resources :deployments
  end
  
  match '/volunteer_introduction', :controller => 'dispatches', :action => 'volunteer_introduction'
  match '/about', :controller => 'dispatches', :action => 'about'
  match '/help', :controller => 'pages', :action => 'help'
  
  root :to => 'dispatches#introduction'

end

app/models/resident.rb
class Resident < ActiveRecord::Base
  has_many :units, :dependent => :destroy
  has_many :signatures, :as => :signatory, :dependent => :destroy
  has_many :proficiencies, :as => :speaker
  has_many :languages, :through => :proficiencies
  has_many :signatures, :as => :signatory, :dependent => :destroy
  has_many :waivers, :through => :signatures
  mount_uploader :image, ProfileImageUploader
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, "first_name", "last_name","primary_phone_number", "encrypted_password", "reset_password_token", "reset_password_sent_at", "remember_created_at", "sign_in_count", "current_sign_in_at", "last_sign_in_at", "current_sign_in_ip", "last_sign_in_ip", "confirmation_token","confirmed_at", "confirmation_sent_at", :date_of_birth, :signed_waiver, :unconfirmed_email, :authentication_token, :created_at, :updated_at, :image, :vehicles, :has_phone, :has_smart_phone, :has_internet_access
  
  before_validation :use_phone_for_email_if_necessary, :on => :create
  
  define_index do
    indexes :first_name
    indexes :last_name
  end
  
  def name
    "#{first_name} #{last_name}"
  end
  
  def use_phone_for_email_if_necessary
    return true unless email.blank?
    return false if primary_phone_number.blank?
    phone_number_without_spaces = primary_phone_number.gsub(/\s/, '')
    self.email = "#{phone_number_without_spaces}@disasterdispatcher.net"
  end
  
  def has_signed_waiver? waiver
    waivers.include? waiver
  end
  
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  before_filter :authenticate_team_admin!, :except => [:show, :edit, :update]
  before_filter :authorize, :only => [:show, :edit, :update]
  # GET /residents
  # GET /residents.json
  def index
    @residents = if params[:order] == 'phone'
      Resident.order('primary_phone_number ' + params[:phone_direction])
    elsif params[:order] == 'first_name'
      Resident.order('first_name ' + params[:first_name_direction])
    elsif params[:order] == 'last_name'
      Resident.order('last_name ' + params[:last_name_direction])
    else
      Resident
    end.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @residents }
    end
  end

  # GET /residents/1
  # GET /residents/1.json
  def show
    @resident = Resident.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resident }
    end
  end

  # GET /residents/new
  # GET /residents/new.json
  def new
    if params[:unit_id]
      session[:unit_id] = params[:unit_id]
    end
    @resident = Resident.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resident }
    end
  end

  # GET /residents/1/edit
  def edit
    @resident = Resident.find(params[:id])
  end

  # POST /residents
  # POST /residents.json
  def populate
    @resident = Resident.new(params[:resident])
    if params[:resident][:password].blank?
      @password = SecureRandom.base64(8)
      @resident.password = @password
      @resident.password_confirmation = @password
      @deliver_password = true
    end

    respond_to do |format|
      if @resident.save
        if session[:unit_id]
          Unit.find(session[:unit_id]).update_attribute(:resident, @resident)
          session[:unit_id] = nil
        end
        if @deliver_password
          ResidentRegistrationMailer.password_generated_notification(@resident, @password).deliver
        end
        session[:resident_id] = @resident.id
        format.html { redirect_to @resident, notice: 'Resident was successfully created.' }
        format.json { render json: @resident, status: :created, location: @resident }
      else
        format.html { render action: "new" }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /residents/1
  # PUT /residents/1.json
  def update
    @resident = Resident.find(params[:id])

    respond_to do |format|
      if @resident.update_attributes(params[:resident])
        format.html { redirect_to @resident, notice: 'Resident was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residents/1
  # DELETE /residents/1.json
  def destroy
    @resident = Resident.find(params[:id])
    @resident.destroy

    respond_to do |format|
      format.html { redirect_to residents_url }
      format.json { head :no_content }
    end
  end
  
  private
  def authorize
    current_team_admin || params[:id] == current_resident.id
  end

end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/residents/_form.html.erb
<%= form_for(@resident) do |f| %>
  <% if @resident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resident.errors.count, "error") %> prohibited this resident from being saved:</h2>

      <ul>
      <% @resident.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.text_field :first_name %>
    <%= f.label :first_name %>
  </div>
  
  <div class="field">
    <%= f.text_field :last_name %>
    <%= f.label :last_name %>
  </div>
  
  <div class="field">
    <%= f.text_field :primary_phone_number %>
    <%= f.label :primary_phone_number %>
  </div>
  
  <div class="field">
    <%= f.text_field :email %>
    <%= f.label :email %>
  </div>
  
  <div class="field">
    <%= f.file_field :image %>
    <%= f.label :image %>
  </div>
  
  <div class="field">
    <%= f.text_field :vehicles %>
    <%= f.label :vehicles %>
  </div>
  
  <div class="field">
    <%= f.check_box :has_phone %>
    <%= f.label :has_phone %>
  </div>
  
  <div class="field">
    <%= f.check_box :has_smart_phone %>
    <%= f.label :has_smart_phone %>
  </div>
  
  <div class="field">
    <%= f.check_box :has_internet_access %>
    <%= f.label :has_internet_access %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/residents/edit.html.erb
<h1>Editing resident</h1>

<%= render 'form' %>

<ul>
  <% @resident.languages.each do |language| %>
    <li><%= language.name %></li>
  <% end %>
  <li>
    <%= form_for @resident.proficiencies.new do |f| %>
      <%= f.select :language_id, options_from_collection_for_select(Language.all, :id, :name), :include_blank => 'Languages Spoken' %>
      <%= f.submit :add %>
      <%= f.hidden_field :speaker_type %>
      <%= f.hidden_field :speaker_id %>
    <% end %>
  </li>
</ul>

app/views/residents/index.html.erb
<h1>Residents list</h1>
<%= button_to 'New Resident', new_resident_path, :method => :get, :class => 'right new_button' %>

<table>
  <tr>
    <th><%= link_to 'First', :order => :first_name, :first_name_direction => (params[:first_name_direction] == 'asc' ? 'desc' : 'asc') %>/
        <%= link_to 'Last', :order => :last_name, :last_name_direction => (params[:last_name_direction] == 'asc' ? 'desc' : 'asc') %></th>
    <th><%= link_to 'primary_phone_number', :order => :phone, :phone_direction => (params[:phone_direction] == 'asc' ? 'desc' : 'asc') %></th>
    <th># of homes</th>
  </tr>
<%= paginate @residents %>
<% @residents.each do |resident| %>
  <tr>
    <td><%= link_to_name resident %></td>
    <td><%= resident.primary_phone_number %></td>
    <td><%= pluralize(resident.units.count, 'unit') %></td>
    <td><%= link_to 'Edit', edit_resident_path(resident) %></td>
    <td><%= link_to 'Destroy', resident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= paginate @residents %>
<br />

app/views/residents/new.html.erb
<h1>New resident</h1>

<%= form_for(@resident, :url => populate_residents_path) do |f| %>
  <% if @resident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resident.errors.count, "error") %> prohibited this resident from being saved:</h2>

      <ul>
      <% @resident.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.text_field :first_name %>
    <%= f.label :first_name %>
  </div>
  
  <div class="field">
    <%= f.text_field :last_name %>
    <%= f.label :last_name %>
  </div>
  
  <div class="field">
    <%= f.text_field :primary_phone_number %>
    <%= f.label :primary_phone_number %>
  </div>
  
  <div class="field">
    <%= f.text_field :email %>
    <%= f.label :email %>
  </div>
  
  <div class="field">
    <%= f.password_field :password %>
    <%= f.label :password, 'New Password' %>
  </div>
  
  <div class="field">
    <%= f.password_field :password_confirmation %>
    <%= f.label :password_confirmation %>
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', residents_path %>

app/views/residents/show.html.erb
<%= image_tag @resident.image, :width => 200 if @resident.image.present? %>

<p>
  <%= @resident.name %>
</p>

<p>
  <%= mail_to @resident.email %>
</p>

<p>
  <%= @resident.primary_phone_number %>
</p>

<p>
  <%= @resident.vehicles %>
</p>

<p>
  <%= @resident.has_phone? ? 'Has phone' : '' %><br>
  <%= @resident.has_smart_phone? ? 'Has smart phone' : '' %><br>
  <%= @resident.has_internet_access? ? 'Has internet access' : '' %>
</p>

<p>
  updated on <%= @resident.updated_at.strftime("%m/%d/%y") %>
</p>

<ul>
  <% @resident.languages.each do |language| %>
    <li><%= language.name %></li>
  <% end %>
</ul>


<div id="units">
  <h3>Dwelling(s) managed by this person:</h3>
  <% @resident.units.each do |unit| %>  
    <%= div_for unit do %>
      <%= link_to_name unit, :full_name %>
    <% end %>
  <% end %>
</div>
<%= link_to 'add dwelling', new_address_path %><br>

<%= link_to 'Edit', edit_resident_path(@resident) %> |
<%= link_to 'Back', residents_path %>