config/routes.rb
Dispatcher::Application.routes.draw do
  
  resources :feedbacks do
    member do
      put :star
    end
  end

  resources :coordinations

  devise_for :coordinators
  resources :coordinators do
    resources :coordinations
  end

  resources :categories

  resources :notes

  resources :proficiencies

  resources :languages do
    resources :teams
  end

  devise_for :residents
  resources :residents do
    collection do
      post :populate
    end
  end

  resources :task_waivers

  resources :jobs do
    resources :notes
    member do
      put :start
      put :finish
    end
    collection do
      post :export
    end
  end

  resources :steps do
    member do
      put 'move_up'
    end
  end

  resources :phase_templates do
    resources :steps
    resources :units do
      post :apply
    end
  end

  resources :signatures do
    collection do
      post :search
    end
  end

  resources :waivers do
    resources :signatures
  end

  resources :deployments

  devise_for :team_admins, :controllers => { :registrations => :team_admin_registrations, :sessions => :sessions }
  resources :team_admins do
    member do
      get 'activate'
      get 'deactivate'
    end
  end

  match '/registration' => 'tasks#registration', :as => 'assistance_registration'
  match '/request' => 'tasks#intake', :as => 'request_task', :via => :post
  match '/legal_intake' => 'tasks#legal_intake', :as => 'legal_intake', :via => :put
  match '/finish_intake' => 'tasks#finish_intake', :as => 'finish_intake', :via => :put
  resources :operations_centers do
    resources :assignments
  end

  resources :assignments

  resources :aptitudes

  resources :dispatches

  resources :tasks

  resources :skills

  resources :roles do
    member do
      post :join
    end
  end

  resources :teams do
    resources :roles
  end

  devise_for :people, :controllers => { :registrations => :registrations, :sessions => :sessions }
  resources :people do
    collection do
      get :home
      get :email_export
    end
  end

  resources :units do
    resources :residents
    resources :jobs
    member do
      get :phase
    end
    collection do
      post :upload
      get :search
    end
  end

  resources :addresses do
    resources :units
    resources :jobs
  end

  resources :streets

  resources :neighborhoods do
    resources :operations_centers
  end

  resources :cities do
    resources :teams
    resources :deployments
  end
  
  match '/volunteer_introduction', :controller => 'dispatches', :action => 'volunteer_introduction'
  match '/about', :controller => 'dispatches', :action => 'about'
  match '/help', :controller => 'pages', :action => 'help'
  
  root :to => 'dispatches#introduction'

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :address
  belongs_to :resident
  belongs_to :note_updated_by, :class_name => 'Person', :foreign_key => :note_updated_by

  has_one :city, :through => :address
  has_one :neighborhood, :through => :address
  has_one :street, :through => :address

  has_many :jobs, :dependent => :destroy
  has_many :tasks, :through => :jobs
  has_many :operations_centers, :dependent => :nullify

  attr_accessible :name, :address_id, :livable, :tenant_is_owner, :legal_needs, :medical_needs, :fema_number, :insurance_situation, :rapid_response_contacted, :power_on, :heater_needed, :needs_met, :resident, :note, :address, :image, :plan_to_return, :need_carbon_monoxide_detector, :year_built, :will_not_be_helped
  mount_uploader :image, ProfileImageUploader
  
  before_create :populate_default_unit_name
  after_destroy :remove_orphaned_address_and_resident
  
  scope :updated, order('updated_at desc')
  
  define_index do
    indexes name
    indexes note
    indexes street.name, :as => :street
    indexes city.name, :as => :city
    indexes address.zip_code
    indexes resident.email
    indexes resident.primary_phone_number
    indexes created_at
    indexes updated_at
    indexes tasks.name, :as => :jobs
  end
  
  def full_name
    "#{name}, #{address.andand.name}"
  end
  
  def full_address
    "#{name}\n#{address.andand.full}"
  end
  
  def populate_default_unit_name
    self.name = 'Main Unit' if name.blank?
  end
  
  def remove_orphaned_address_and_resident
    address.destroy if address.units.empty?
    resident.destroy if resident.units.empty?
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_filter :authenticate_team_admin!, :only => [:index, :edit, :update, :destroy]
  before_filter :check_authorization, :only => :show

  def search
    @units = Unit.search(params[:query]).page(params[:page])
    render :action => :index
  end
  
  # GET /units
  # GET /units.json
  def index
    @units = if params[:order] == 'updated'
      Unit.order('updated_at ' + params[:updated_direction])
    elsif params[:order] == 'created'
      Unit.order('created_at ' + params[:created_direction])
    elsif params[:order] == 'note_updated'
      Unit.order('note_updated_at ' + params[:note_updated_direction])
    elsif params[:order] == 'first_name'
      Unit.joins(:resident).order('residents.first_name ' + params[:first_name_direction])
    elsif params[:order] == 'last_name'
      Unit.joins(:resident).order('residents.last_name ' + params[:last_name_direction])
    elsif params[:order] == 'name'
      Unit.order('name ' + params[:name_direction])
    elsif params[:order] == 'address'
      Kaminari.paginate_array(Address.joins(:street, :units).order("streets.name #{params[:address_direction]}").order("addresses.street_number #{params[:address_direction]}").map(&:units).flatten)
    else
      Unit.order('created_at desc')
    end.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @units }
    end
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/new
  # GET /units/new.json
  def new
    @unit = Unit.new :address_id => params[:address_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end
  
  def phase
    @unit = Unit.find params[:id]
  end

  def apply
    @unit = Unit.find params[:unit_id]
    @phase_template = PhaseTemplate.find params[:phase_template_id]
    @phase_template.steps.each do |step|
      @unit.jobs.create :task_id => step.task_id
    end
    redirect_to @unit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(params[:unit])
    if session[:resident_id]
      @unit.resident_id = session[:resident_id]
      session[:resident_id] = nil
    end

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.json
  def update
    @unit = Unit.find(params[:id])
    
    if params[:unit].andand[:note].present? && (@unit.note.blank? || (@unit.note != params[:unit][:note]))
      @unit.note_updated_by = current_person
      @unit.note_updated_at = Time.now
    end

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end
  
  def upload
    csv = params[:csv][:data]
    data = csv.read
    # CSV.parse(data, :headers => :first_row) do |unit|
    #   if unit['Address'] =~ /(\d+)\s+([\w\s]+)/
    #     street_number = $1
    #     street_name = $2
    #   else
    #     street_number = unit['Address']
    #   end
    #   neighborhood = Neighborhood.find_or_create_by_name(unit['Neighborhood']) if unit['Neighborhood'].present?
    #   street = Street.find_or_create_by_name street_name
    #   address = Address.find_or_create_by_street_number street_number, :street => street, :neighborhood => neighborhood
    #   unit['Contact Name'] =~ /([\w\s]+)\s+([\w\-]+)/
    #   first_name = $1
    #   last_name = $2
    #   resident = Resident.create :first_name => first_name, :last_name => last_name, :email => "#{first_name.andand.gsub(/\s/, '')}-#{last_name}-#{SecureRandom.urlsafe_base64(4)}@disasterdispatcher.net", :password => 'password', :password_confirmation => 'password', :primary_phone_number => unit['Phone']
    #   unit = Unit.create :address => address, :name => unit['Name'], :resident => resident, :power_on => (unit['Power On?'] == 'Yes'), :legal_needs => unit['Legal Assistance'], :heater_needed => (unit['Is a Heater Needed?'] == 'Yes'), :medical_needs => unit['Healthcare Needs'], :insurance_situation => unit['FEMA Visited House? What color tag? Insurance?'], :note => "Category:#{unit['Category']}\nSpoke to Resident:#{unit['Spoke to Resident']}\nSupplies:#{unit['Supplies']}\nLabor:#{unit['Labor?']}\nPartnering with F2F:#{unit['Partnering with F2F']}\nComments:#{unit['Comments']}\nDate:#{unit['Date']}\nTime:#{unit['Time']}\nScheduling:#{unit['Scheduling']}\nHousing Assistance:#{unit['Housing Assistance']}\nCrew Leader:#{unit['Crew Leader']}"
    # end
    

    CSV.parse(data, :headers => :first_row) do |survey|
      if survey['Street'] =~ /(\d+)\s+([\w\s]+)/
        street_number = $1
        street_name = $2
      end
      street = Street.find_or_create_by_name street_name
      address = Address.find_or_create_by_street_number street_number, :street => street
      resident = Resident.create :first_name => survey['First Name'], :last_name => survey['Last Name'], :email => survey['Email'], :password => 'password', :password_confirmation => 'password', :primary_phone_number => survey['Phone']
      Unit.create :address => address, :name => 'Main Unit', :resident => resident, :power_on => (survey['Do you have electricity?'] == 'YES'), :legal_needs => survey['Does anyone need to speak with a lawyer? '], :heater_needed => (survey['Do you have heat?'] == 'NO'), :medical_needs => survey['Does anyone in your household need medical attention? '], :insurance_situation => survey['Name of insurers:']
    end
    redirect_to :action => :index
  end
  
  private
  def check_authorization
    @unit = Unit.find params[:id]
    return true if @unit.resident == current_resident
    return true if current_team_admin
  end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.select :address_id, options_from_collection_for_select(Address.all, :id, :name, @unit.address_id) %>
  </div>
  <div class="field">
    <%= f.label :legal_needs %><br />
    <%= f.text_field :legal_needs %>
  </div>
  <div class="field">
    <%= f.label :medical_needs %><br />
    <%= f.text_field :medical_needs %>
  </div>
  <div class="field">
    <%= f.label :insurance_situation %><br />
    <%= f.text_field :insurance_situation %>
  </div>
  <div class="field">
    <%= f.label :fema_number %><br />
    <%= f.text_field :fema_number %>
  </div>
  <div class="field">
    <%= f.label :livable %><br />
    <%= f.check_box :livable %>
  </div>
  <div class="field">
    <%= f.label :needs_met %><br />
    <%= f.check_box :needs_met %>
  </div>
  <div class="field">
    <%= f.label :power_on %><br />
    <%= f.check_box :power_on %>
  </div>
  <div class="field">
    <%= f.label :heater_needed %><br />
    <%= f.check_box :heater_needed %>
  </div>
  <div class="field">
    <%= f.label :tenant_is_owner %><br />
    <%= f.check_box :tenant_is_owner %>
  </div>
  <div class="field">
    <%= f.label :rapid_response_contacted %><br />
    <%= f.check_box :rapid_response_contacted %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note, :size => '30x3' %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :year_built %><br>
    <%= f.date_select :year_built, :discard_month => true, :start_year => Time.now.year, :end_year => 1800, :include_blank => true %>
  </div>
  
  <% if current_team_admin %>
    <div class="field">
      <%= f.label :will_not_be_helped %><br>
      <%= f.check_box :will_not_be_helped %>
    </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Homes</h1>

<%= button_to 'New Unit', new_unit_path, :method => :get, :class => 'right new_button' %>
<%= form_tag search_units_path, :method => :get, :class => 'search_bar' do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag :search %>
<% end %>
<table>
  <tr>
    <th><%= link_to 'Name', :order => :name, :name_direction => (params[:name_direction] == 'asc' ? 'desc' : 'asc') %></th>
    <th><%= link_to 'Address', :order => :address, :address_direction => (params[:address_direction] == 'asc' ? 'desc' : 'asc') %></th>
    <th><%= link_to 'First', :order => :first_name, :first_name_direction => (params[:first_name_direction] == 'asc' ? 'desc' : 'asc') %>/
      <%= link_to 'Last', :order => :last_name, :last_name_direction => (params[:last_name_direction] == 'asc' ? 'desc' : 'asc') %></th>
    <th></th>
    <th></th>
    
    <th style="width:200px;">Notes</th>
    <th><%= link_to 'Note Update', :order => :note_updated, :note_updated_direction => (params[:note_updated_direction] == 'asc' ? 'desc' : 'asc') %></th>
    
    <th><%= link_to 'Updated', :order => :updated, :updated_direction => (params[:updated_direction] == 'asc' ? 'desc' : 'asc') %></th>
    <th><%= link_to 'Date Created', :order => :created, :created_direction => (params[:created_direction] == 'asc' ? 'desc' : 'asc') %></th>
  </tr>
<%= paginate @units %>
<% @units.each do |unit| %>
  <tr class="<%= cycle 'light-gray', 'white' %>">
    <td><%= link_to_name unit %></td>
    <td><%= link_to_name unit.address %></td>
    <td>
      <% if unit.resident.present? %>
        <%= link_to_name unit.resident %>
      <% else %>
        <%= link_to 'xadd resident', new_unit_resident_path(unit) %>
      <% end %>
    </td>
    <td><%= link_to pluralize(unit.jobs.incomplete.count, 'job'), unit_jobs_path(unit) %></td>
    <td><%= link_to 'Show details', unit %></td>
    <td><%= unit.note %></td>
    <td><%= "updated #{time_ago_in_words unit.note_updated_at} ago by #{unit.note_updated_by.name}" if unit.note_updated_by %></td>
    <td><%= unit.updated_at.strftime("%m/%d/%y %I %p") %></td>
    <td><%= unit.created_at.strftime("%m/%d/%y") %></td>
    <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
    <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= paginate @units %>
<br />


<%= link_to_function 'upload csv', "$('#upload_form').show()" %>
<div id="upload_form">
  <%= form_tag upload_units_path, :multipart => true do %>
    <%= file_field :csv, :data %>
    <%= submit_tag 'Load' %>
  <% end %>
</div>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/phase.html.erb
<%= div_for @unit do %>
  <%= @unit.name %><br>
  Existing jobs(complete):
  <% @unit.jobs.complete.each do |job| %>
    <%= div_for job do %>
      <%= link_to_name job %>
    <% end %>
  <% end %>

  Existing jobs(started):
  <% @unit.jobs.incomplete.each do |job| %>
    <%= div_for job do %>
      <%= link_to_name job %>
    <% end %>
  <% end %>
  
  Existing jobs(unstarted):
  <% @unit.jobs.unstarted.each do |job| %>
    <%= div_for job do %>
      <%= link_to_name job %>
    <% end %>
  <% end %>
<% end %>

Phases
<% PhaseTemplate.alphabetical.each do |phase| %>
  <%= div_for phase do %>
    <%= link_to_name phase %>
    <%= link_to 'apply', phase_template_unit_apply_path(phase, @unit), :method => :post %>
    <ol>
      <% phase.steps.each do |step| %>
        <li>
          <%= link_to_name step %>
          <%= link_to 'apply', jobs_path(:job => {:task_id => step.task_id, :unit_id => @unit.id}), :method => :post %>
        </li>
      <% end %>
    </ol>
  <% end %>
<% end %>

app/views/units/show.html.erb
<i>Please note that jobs (even after scheduling) are staffed by volunteers and rely on volunteers showing up.  We will do our best to help you, but can make no guarantees.</i>
<table>
  <tr>
    <th></th>
    <th>completed</th>
    <th>date</th>
  </tr>
  <div id="requested_jobs">
    <%= link_to 'show all jobs', unit_jobs_path(@unit) %>
    <% @unit.jobs.each do |job| %>
      <%= div_for job do %>
        <tr>
          <td>
            <% if current_team_admin %>
              <%= link_to_name job %>
              <%= job.teams.map { |team| link_to_name team }.join.html_safe %>
              <%= form_for job.dispatches.new, :remote => true do |f| %>
                <%= f.select :team_id, options_from_collection_for_select(Team.alphabetical, :id, :name), :include_blank => true %>
                <%= f.submit :dispatch %>
                <%= f.hidden_field :job_id %>
              <% end %>
              <%= button_to '[x]', job_path(job), :method => :delete, :confirm => 'Ready to cancel this job?' %>
            <% else %>
              <%= job.name %>
            <% end %>
          </td>
        <% if job.actual_end.present? %>
          <td>√</td>
          <td><%= job.actual_end.strftime("%m/%d/%y") %></td>
        <% end %>
      <% end %>
    <% end %>
  </div>
</table>
<div id="nominate_tasks">
  <span id="instructions">If your home needs one or more of these jobs done, click on them (the page will reload each time).</span>
  <% (Task.common_tasks - @unit.tasks).each do |task| %>
    <%= link_to task.name, jobs_path(:job => {:task_id => task.id, :unit_id => @unit.id}), :method => :post %><br>
  <% end %>
</div>

<%= clearfix %>
<p>
  <b>Resident:</b>
  <% if @unit.resident.present? %>
    <%= link_to_name @unit.resident %>
  <% else %>
    <%= link_to 'add resident', new_unit_resident_path(@unit) %>
  <% end %>
</p>

<p>
  <b>Phone:</b>
  <%= @unit.resident.andand.primary_phone_number %>
</p>  

<p>
  <%= image_tag @unit.image, :width => 400 if @unit.image.present? %>
</p>

<p>
  <b>Name:</b>
  <%= @unit.name %>
</p>

<p>
  <b>Address:</b>
  <%= link_to_name @unit.address %>
</p>

<p>
  <b>Livable:</b>
  <%= @unit.livable %>
</p>

<p>
  <b>Plans to return:</b>
  <%= @unit.plan_to_return %>
</p>

<p>
  <b>Year built:</b>
  <%= @unit.year_built.andand.strftime("%Y") %>
</p>

<p>
  <b>Tenant is owner:</b>
  <%= @unit.tenant_is_owner %>
</p>

<p>
  <b>Power is on:</b>
  <%= @unit.power_on %>
</p>

<p>
  <b>Needs are met:</b>
  <%= @unit.needs_met %>
</p>

<p>
  <b>Heater needed:</b>
  <%= @unit.heater_needed %>
</p>

<p>
  <b>Carbon Monoxide Detector needed:</b>
  <%= @unit.need_carbon_monoxide_detector %>
</p>

<p>
  <b>Legal needs:</b>
  <%= @unit.legal_needs %>
</p>

<p>
  <b>Medical needs:</b>
  <%= @unit.medical_needs %>
</p>

<p>
  <b>Insurance situation:</b>
  <%= @unit.insurance_situation %>
</p>

<p>
  <b>Rapid Response contacted:</b>
  <%= @unit.rapid_response_contacted %>
</p>

<p>
  <b>FEMA id</b>
  <%= @unit.fema_number %>
</p>

<p>
  <b>Notes:</b>
  <%= text_to_html @unit.note.to_s %>
</p>

<% if @unit.note_updated_by %>
  <p>
    last updated by <%= @unit.note_updated_by.name %> <%= time_ago_in_words(@unit.note_updated_at) %>
  </p>
<% end %>

<p>
  updated on <%= @unit.updated_at.strftime("%m/%d/%y") %>
</p>
  
<% @unit.jobs.each do |job| %>
  <%= div_for job do %>
    <%= link_to_name job %>
    (<%= job.scheduled_start.andand.strftime("%I:%M %p on %A, %b %d") %>)
  <% end %>
<% end %>

<%= link_to 'add phase of tasks', phase_unit_path(@unit) %>

<%= gmaps(:markers => {:data => @unit.address.andand.to_gmaps4rails}, :map_options => {:auto_zoom => false, :zoom => 14, :detect_location => true}) %>


<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>